Innervator2Locals = {
	--Printstuff
	["PrintFirstLogin"] = "This is your first login with this addon. Target set to yourself: ",
	["PrintNoTarget"] = "No Innervate target specified.",
	["PrintMacroPlayerInCombat"] = "You are in combat. Will create macro when combat finished.",
	["PrintSoundsDisabled"] = "Sounds are off. Use [|cff00FF00/i2 sound|r] to turn them on.",
	["PrintSoundsEnabled"] = "Sounds are on. Use [|cff00FF00/i2 sound|r] again to turn them off.",
	["PrintAddonDidNotLoadup"] = "The addon did not load up because you don't know the Innervate spell.",
	["PrintAddonIsAlreadyDisabled"] = "Addon is already disabled.",
	["PrintAddonIsAlreadyEnabled"] = "Addon is already enabled.",
	["PrintAddonDisabled"] = "Disabled. Type [|cff00FF00/i2 on|r] to enable the addon.",
	["PrintAddonEnabled"] = "Enabled. Type [|cff00FF00/i2 off|r] to disable the addon.",
	["PrintEditmacroNoTargetFound"] = "Found no Innervate target in the macro. Use /i2 as a dummy at least once.",
	["PrintEditmacroCleared"] = "Standard code for the macro was restored.",
	["PrintEditMacroError"] = "Error! Could not edit macro.",
	["PrintEditmacroSaved"] = "The new macro was saved. You can create the fitting macro with [|cff00FF00/i2 macro|r] now.",
	["PrintEditmacroNotCorrect"] = "Could not read macro or the given macro is to short (at least 10 letters).",
	["PrintEditmacroNotFound"] = "Can not find the macro!",
	["PrintMacroForEditCreated"] = "Created the macro (I2InputMacroText), you can now go and edit it. After you finish: Type [|cff00FF00/i2 macro save|r] to let the addon know that you are done. Use /i2 in your macro as a dummy for your Innervate target, the addon will always replace it with the current target.",
	["PrintMacroNoSpace"] = "Could not create macro. There is not enough space for a new macro.",
	["PrintMacroCreated"] = "Macro was created or edited: [|cffFF7D0A|HInnervator2|hInnervator2Macro|h|r]. Click on the name to pick up the macro button.",
	["PrintSetTarget1"] = "Innervate target set to ",
	["PrintSetTarget2"] = " Type [|cff00FF00/i2 test|r] to send a who query with the saved name (to check spelling).",
	["PrintUnknownCommand1"] = "Unknown command: |cff5555FF",
	["PrintUnknownCommand2"] = "Type [|cff00FF00/i2 help|r] to view the help (type the command without the square brackets).",
	["PrintTarget"] = "Your current Innervate target is ",

	--ChatSpamer
	["PrintChatSpam"] = "|cffFF0000Use your Innervate on|r ",
	["PrintChatSpamOutOfRange"] = "|cffFF0000Out of range for Innervate, move to|r ",
	["PrintChatSpamManaPot"] = "|cff5555FFUse your Mana Potion now!|r",

	--GUI
	["OptionsButtonHelp"] = "Help",
	["SelectDrop_CLOSE_INFO_TEXT"] = "Close",
		--mainpanel
	["OptionsStringInfo"] = " options.\n You can type [|cff00FF00/i2 help|r] for help about the slash commands (without the square brackets).",
	["OptionsCheckEnableAddon_LABEL"] = "Enable Addon",
	["OptionsCheckEnableAddon_HINT"] = "Enables/disables the addon temporarly.",
	["OptionsStringSetTarget"] = "Set new Innervate target:",
	["OptionsButtonSetTarget"] = "Ok",
	["OptionsWarningByThreshold_LABEL"] = "Warning by threshold",
	["OptionsWarningByThreshold_HINT"] = "If enabled the warning for innervate will fire at a specific threshold based on your Innervate target's max. mana pool.",
	["OptionsWarningByBest_LABEL"] = "Earliest warning possible",
	["OptionsWarningByBest_HINT"] = "If enabled the warning for innervate will fire as soon as possible, which is as soon as the innervate would not waste any mana.",
	["OptionsSliderThresholdLabel"] = "Threshold: ",

		--warningpanels
	["Innervator2Warning1Panel_NAME"] = "Warning1",
	["Innervator2Warning2Panel_NAME"] = "Warning2",
	["OptionsWarning1StringInfo"] = " |cffFFFFFFwarning1|r options.\n You can type [|cff00FF00/i2 help|r] for help about the slash commands (without the square brackets).",
	["OptionsWarning2StringInfo"] = " |cffFFFFFFwarning2|r options.\n You can type [|cff00FF00/i2 help|r] for help about the slash commands (without the square brackets).",
	["OptionsCheckSound_LABEL"] = "Sound",
	["OptionsCheckSound_HINT"] = "Enable/disable sounds played by this addon.",
	["OptionsWarningStringSound1"] = "Warning sound:",
	["OptionsWarningStringSound2"] = "OutOfRange sound:",
	["OptionsWarningSelectSounds"] = "Sounds:",
	["OptionsWarningSoundsReindeer"] = "Reindeer",
	["OptionsWarningSoundsPVPWarningAlliance"] = "PVPWarningAlliance",
	["OptionsWarningSoundsPVPWarningHorde"] = "PVPWarningHorde",
	["OptionsWarningSoundsTimeForFun"] = "TimeForFun",
	["OptionsWarningSoundsThekal"] = "Thekal",
	["OptionsWarningSoundsLevelUp"] = "LevelUp",
	["OptionsWarningSoundsSimonGame"] = "SimonGame",
	["OptionsWarningButtonSave"] = "Save",
	["OptionsWarningButtonTest"] = "Test",
	["OptionsWarningTestMessage"] = "This is a test message.",
	["OptionsWarningSoundtestPlayed"] = "' played.",
	["OptionsWarningStringChatframe"] = "Output Chatframe:",
	["OptionsWarningChatframesDefault"] = "Default Chatframe",
	["OptionsWarningChatframesError"] = "Error Frame",
	["OptionsWarningChatframesDBM"] = "DBM Frame",
	["OptionsWarningIcon"] = "Icon:",
	["OptionsWarningIconsInnervate"] = "Innervate",
	["OptionsWarningIconsStar"] = "Star",
	["OptionsWarningIconsCircle"] = "Circle",
	["OptionsWarningIconsDiamond"] = "Diamond",
	["OptionsWarningIconsTriangle"] = "Triangle",
	["OptionsWarningIconsMoon"] = "Moon",
	["OptionsWarningIconsSquare"] = "Square",
	["OptionsWarningIconsCross"] = "Cross",
	["OptionsWarningIconsSkull"] = "Skull",
	["OptionsWarningIconsSkull2"] = "Skull2",
	["OptionsWarningIconsTreeOfLife"] = "Tree Of Life",
	["OptionsWarningIconsReplenishment"] = "Replenishment",
	["OptionsWarningIconsNone"] = "None",
	["OptionsWarningChatframeSaved"] = "Chatframe was changed to: ",
	["OptionsWarningIconSaved"] = "Icon was changed to: ",
	["OptionsWarningLineCount"] = "Line count:",
	["OptionsWarningSingleLine"] = "Single Line",
	["OptionsWarningDoubleLine"] = "Double Line",
	["OptionsWarningTripleLine"] = "Triple Line",
	["OptionsWarningLineCountSaved"] = "New Line count saved: ",
	["OptionsWarningFrameflash_NAME"] = "Frameflash",
	["OptionsWarningFrameflash_LABEL"] = "Activate this to flash the edges of the frame everytime the innervate warning is triggered.",
	["OptionsWarningSound1Saved"] = "New Warning sound saved: ",
	["OptionsWarningSound2Saved"] = "New OutOfRange sound saved: ",
	["OptionsWarningFlashColor"] = "Flash color:",
	["OptionsWarningWrongInputColor"] = "Wrong color input.",
	["OptionsWarningColorPreview"] = "Preview:",
	["OptionsWarningErrorColorpickerShown"] = "Colorpicker is already shown.",
	["OptionsWarningFrameflashColorSaved"] = "New frame flash color saved.",
	["OptionsWarningFrameflashSave_TOOLTIP"] = "Input must be three values in the range from 0 to 1, seperated with a space. They represent a RGB color (red,green,blue). An example input could be: '0 0.5 1', without the quotationmarks.",
	["OptionsWarningLineCount_TOOLTIP"] = "Decides how many lines one warning should have.",

		--macropanel
	["Innervator2MacroPanel_NAME"] = "Macro (advanced)",
	["OptionsMacroStringInfo"] = " |cffFFFFFFmacro|r options.\n You can type [|cff00FF00/i2 help|r] for help about the slash commands (without the square brackets).",
	["OptionsMacroPrintHyperlinkMacro"] = "Hyperlink",
	["OptionsMacroEditTheMacro"] = "Edit macro",
	["OptionsMacroSaveTheMacro"] = "Save macro",
	["OptionsMacroInputMacroTextInfo"] = "This is the current macro code:",
	["OptionsMacroPrintHyperlink"] = "Macro: [|cffFF7D0A|HInnervator2|hInnervator2Macro|h|r]. Click on the name to pick up the macro button (does not work in combat).",

		--manapotpanel
	["Innervator2ManaPotPanel_NAME"] = "Mana Potion",
	["OptionsManaPotStringInfo"] = " |cffFFFFFFmana pot|r options.\n You can type [|cff00FF00/i2 help|r] for help about the slash commands (without the square brackets).",
	["OptionsCheckManaPot_HINT"] = "If enabled the addon will also remind you to use your mana potion at a specific threshold.",
	["OptionsCheckManaPot_LABEL"] = "Enable ManaPot",
	["OptionsManaPotSoundSaved"] = "Manapotion sound saved:",

		--buttonhelp
	["OptionsBH1_1"] = "You can disable the addon temporarily. When disabled warnings will not fire. Status can be changed in combat.",
	["OptionsBH1_2"] = "You can set your innervate target freely to any other player and the addon will check that players mana instead of yours. Innervator2 can warn you when you are too far away from that player then.",
	["OptionsBH2"] = "Enables/disabled the addon based on your spec or location. You can always change the status with [|cff00FF00/i2 disable|r] or [|cff00FF00/i2 enable|r].",
	["OptionsBH3"] = "You can either enable 'Earliest warning possible' (the innervate warning is fired as early as possible, i.e. you wont waste any mana) or 'Warning by threshold' (the innervate warning is fired based on a fixed mana percentage threshold).",
	["OptionsWarning1BH"] = "The warnings all come with a little sound. You can enable/disable them here. You can select a default sound with the '!' button. Warning Sound: The sound played when you should innervate the innervate target. OutOfRange sound: The sound played when you should innervate the innervate target but are out of range to do so.",
	["OptionsWarning2BH1"] = "Frameflash: When enabled the edges of the screen will flash when a warning is fired. To change the color of the flash click on the '!' button and select a color.",
	["OptionsWarning2BH2"] = "Output Chatframe: The chat frame to which the (text) warnings will be posted to. The 'Default Chatframe' is the chat frame where your general and trade channels should be. The 'Error Frame' is a frame in the upper middle of the screen. You can also select 'DBM Frame' which is in the middle of the screen, too. But it has a better looking font. You can also select an icon, so that the (text) warnings stand more out.",
	["OptionsMacroBH"] = "(advanced) The addon can provide a macro for the user which is updated everytime the innervate target is changed. Look in the documentation for more information on this.",
	["OptionsManaPotBH"] = "The addon can remind you to use a mana potion in a fight. It will warn you based on a mana percentage threshold. You can select a warning sound for the mana potion warning, too. This only works when you have one of those mana potions ready to use in your bag: Potion of Concentration, Mysterious Potion or Mythical Mana Potion.",

	--THEHELP
	["HELP1"] = "Displaying help...",
	["HELP2"] = "All commands are typed without the square brackets.",
	["HELP3"] = "You can use [|cff00FF00/i2|r] or [|cff00FF00/innervator2|r] for all commands.",
	["HELP4"] = "Use [|cff00FF00/i2 disable|r] to (temporarily) disable this addon. Restarting the game or reloading the UI will reenable it.",
	["HELP5"] = "Use [|cff00FF00/i2 enable|r] to enable this addon when you disabled it previously.",
	["HELP6"] = "Use [|cff00FF00/i2 print|r] to show your current Innervate target. This is the player you want to give your Innervate to and whose mana will be watched therefore. You can set yourself as Innervate target.",
	["HELP7"] = "Use [|cff00FF00/i2 set|r |cffFF0000xxx|r] to set a new Innervate target, where [|cffFF0000xxx|r] is the name of the player you want to give your Innervate to.",
	["HELP8"] = "Use [|cff00FF00/i2 test|r] to send a /who query to the server with the current Innervate target for the purpose of a spelling check.",
	["HELP9"] = "The addon will warn you with a sound when you should cast your Innervate. To toggle playing of sounds type [|cff00FF00/i2 sound|r].",
	["HELP10"] = "For more options you can check out the GUI with [|cff00FF00/i2 opt|r].",
	["HELP11"] = "...end of help."
}